-- This migration was generated by `supabase db pull` to sync the remote schema
-- It has already been applied to both remote and local databases
-- This file is a placeholder to keep the migration history consistent

-- No-op migration - schema already applied during db pull/reset
SELECT 1;
